[Issue-1083][client] kafka sink properties not enable
DataLinkDC/dinky pull request #1125
Opened 2022-10-20 08:58 UTC by boolean-dev

## 修复 kafka sink 配置 peoperties 未生效问题

- DorisSink 重写了 `getProperties()`  方法
- flink 1.13之前版本
    - 使用 `FlinkKafkaProducer` 含 perperties 构造参数创建 Sink
- flink 1.14 之后的版本
    - 使用 `KafkaSink.setKafkaProducerConfig()` 注入

> 目前我本人只测试了 1.14 版本的效果，其它版本未进行测试

2022-10-20 14:40 UTC, aiwenmo requested changes

2022-10-20 14:40 UTC, aiwenmo commented on dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/kafka/KafkaSinkBuilder.java
> +        }
What is the meaning of this code?
Please use the variable naming method with business significance.

2022-10-21 01:03 UTC, boolean-dev commented on dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/kafka/KafkaSinkBuilder.java
> +        }
这个是从 `FlinkKafkaProducer` 里面粘过来的方法，主要的功能是把 kafka brokerList 字符串转换为数组，忘记改参数名了
![9DBB76BE0A98F5E2922EE3C04EC64156](https://user-images.githubusercontent.com/20177406/197087408-5bbd5c9e-ee03-42e9-a1f8-aa2d0cb32677.png)

2022-10-21 05:39 UTC, aiwenmo commented on dlink-client/dlink-client-1.11/src/main/java/com/dlink/cdc/kafka/KafkaSinkBuilder.java
> +        }
那请再追加下修改，然后直接 Commit 会自动追加到这个 PR 里。

2022-10-21 12:45 UTC, aiwenmo commented
您好，您把您的kafka修复的PR给覆盖了，kafka PR 被 merge 后再提交后续的PR

2022-10-23 13:59 UTC, aiwenmo approved these changes
LGTM

2022-10-23 13:59 UTC, merged

2022-10-24 01:51 UTC, boolean-dev commented
好的，那我后续再重新申请一个 PR吧

2022-10-24 02:51 UTC, aiwenmo commented
> ## 修复 kafka sink 配置 peoperties 未生效问题
> * DorisSink 重写了 `getProperties()`  方法
> * flink 1.13之前版本
>   
>   * 使用 `FlinkKafkaProducer` 含 perperties 构造参数创建 Sink
> * flink 1.14 之后的版本
>   
>   * 使用 `KafkaSink.setKafkaProducerConfig()` 注入
> 
> > 目前我本人只测试了 1.14 版本的效果，其它版本未进行测试

这些内容再重新提交一个 PR。

2022-10-24 02:53 UTC, aiwenmo commented
> > ## 修复 kafka sink 配置 peoperties 未生效问题
> > 
> > * DorisSink 重写了 `getProperties()`  方法
> > * flink 1.13之前版本
> >   
> >   * 使用 `FlinkKafkaProducer` 含 perperties 构造参数创建 Sink
> > * flink 1.14 之后的版本
> >   
> >   * 使用 `KafkaSink.setKafkaProducerConfig()` 注入
> > 
> > > 目前我本人只测试了 1.14 版本的效果，其它版本未进行测试
> 
> 这些内容再重新提交一个 PR。

- [X] #1139