reformat jobmanager.java file, improve code readability and some other trick refaction.
DataLinkDC/dinky pull request #1133
Opened 2022-10-21 13:00 UTC by leechor

## Purpose of the pull request

## Brief change log

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

2022-10-21 13:05 UTC, aiwenmo commented
Hi. It's a good PR. Please resolve the code conflict. thx.

2022-10-21 13:18 UTC, aiwenmo approved these changes
You can submit the file optimization first, such as Asserts.java, SqlType.java, Operations.java, GatewayType.java.

2022-10-21 13:18 UTC, aiwenmo commented on dlink-app/dlink-app-base/src/main/java/com/dlink/app/flinksql/Submiter.java
> +            String statement = FlinkInterceptor.preTreatStatement(executor, item);
Pretreat statement, not pre treat statement.

2022-10-21 13:21 UTC, aiwenmo commented
I don't think it's necessary to change pretreatStatement into preTreatStatement.

2022-10-21 13:28 UTC, leechor commented
> 

my IDEAdictionary don't have this word, sorry, I change back to it

2022-10-22 05:05 UTC, aiwenmo commented
> > 
> 
> my IDEA dictionary don't have this word, sorry, I change back to it

Look forward to your optimization.

2022-10-22 10:32 UTC, leechor commented
> > > 
> > 
> > 
> > my IDEA dictionary don't have this word, sorry, I change back to it
> 
> Looking forward to your optimization.

I have submitted [that](https://github.com/DataLinkDC/dlink/pull/1135) independently,

2022-10-23 11:27 UTC, aiwenmo commented
> > > > 
> > > 
> > > 
> > > my IDEA dictionary don't have this word, sorry, I change back to it
> > 
> > 
> > Looking forward to your optimization.
> 
> I have submitted [that](https://github.com/DataLinkDC/dlink/pull/1135) independently,

Sorry, I didn't see your code submission. Please check your commit.

2022-10-23 13:44 UTC, leechor commented
> > > > > 
> > > > 
> > > > 
> > > > my IDEA dictionary don't have this word, sorry, I change back to it
> > > 
> > > 
> > > Looking forward to your optimization.
> > 
> > 
> > I have submitted [that](https://github.com/DataLinkDC/dlink/pull/1135) independently,
> 
> Sorry, I didn't see your code submission. Please check your commit.

I don't understand your mean, I have opened a new [pull request](https://github.com/DataLinkDC/dlink/pull/1135)

2022-10-23 14:05 UTC, aiwenmo commented
> > > > > > 
> > > > > 
> > > > > 
> > > > > my IDEA dictionary don't have this word, sorry, I change back to it
> > > > 
> > > > 
> > > > Looking forward to your optimization.
> > > 
> > > 
> > > I have submitted [that](https://github.com/DataLinkDC/dlink/pull/1135) independently,
> > 
> > 
> > Sorry, I didn't see your code submission. Please check your commit.
> 
> I don't get your mean, I have opened a new [pull request](https://github.com/DataLinkDC/dlink/pull/1135)

-[X] #1135

2022-10-24 07:54 UTC, leechor commented
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > my IDEA dictionary don't have this word, sorry, I change back to it
> > > > > 
> > > > > 
> > > > > Looking forward to your optimization.
> > > > 
> > > > 
> > > > I have submitted [that](https://github.com/DataLinkDC/dlink/pull/1135) independently,
> > > 
> > > 
> > > Sorry, I didn't see your code submission. Please check your commit.
> > 
> > 
> > I don't get your mean, I have opened a new [pull request](https://github.com/DataLinkDC/dlink/pull/1135)
> 
> * [x]  [refactor: some trick modification #1135](https://github.com/DataLinkDC/dlink/pull/1135)

@aiwenmo doesn't match checkstyle.xml and spotless_dlink_formatter.xml in the style directory. checkstyle still reports error report error after run spotless:apply.

2022-10-24 13:50 UTC, aiwenmo commented
> doesn't match checkstyle.xml and spotless_dlink_formatter.xml in the style directory. checkstyle still reports error report error after run spotless:apply.

Try updating to the latest code.

2022-10-25 01:07 UTC, aiwenmo requested changes
Thank you very much for your optimization. Because the file named JobManager.java is complex and critical, and requires a lot of unit tests to verify its interface, please do not optimize it first. Later, I will reconstruct it.

2022-10-25 01:52 UTC, leechor commented
> Thank you very much for your optimization. Because the file named JobManager.java is complex and critical, and requires a lot of unit tests to verify its interface, please do not optimize it first. Later, I will reconstruct it.

ok, I close it.

2022-10-25 01:52 UTC, closed without merging

2022-10-25 04:24 UTC, leechor commented
> Thank you very much for your optimization. Because the file named JobManager.java is complex and critical, and requires a lot of unit tests to verify its interface, please do not optimize it first. Later, I will reconstruct it.

@aiwenmo I left [JobManager](https://github.com/leechor/dlink/blob/ldev_jobmanager/dlink-core/src/main/java/com/dlink/job/JobManager.java) for your reference. it merged the new dev.

2022-10-25 07:58 UTC, aiwenmo commented
> > Thank you very much for your optimization. Because the file named JobManager.java is complex and critical, and requires a lot of unit tests to verify its interface, please do not optimize it first. Later, I will reconstruct it.
> 
> @aiwenmo I left [JobManager.java](https://github.com/leechor/dlink/blob/ldev_jobmanager/dlink-core/src/main/java/com/dlink/job/JobManager.java) for your reference. it merged the new dev.

thx. The optimization of other files can be submitted first.