[Fix][Upgrade]0.7.0 upgrade 0.7.1 all bug
DataLinkDC/dinky pull request #1535
Opened 2023-01-11 09:19 UTC by zackyoungh

## Purpose of the pull request

0.7.0 upgrade 0.7.1 all bug

2023-01-11 13:28 UTC, aiwenmo approved these changes
LGTM

2023-01-11 13:31 UTC, aiwenmo requested changes
Check sql.

2023-01-11 13:31 UTC, aiwenmo commented on dlink-doc/sql/dinky.sql
> +                                      `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'id',
Please check sql.

2023-01-12 03:35 UTC, zhu-mingye reviewed
LGTM

2023-01-12 04:31 UTC, closed without merging