[Optimization-1548][metadata] Optimize datasource registration should can save config before validate
DataLinkDC/dinky pull request #1566
Opened 2023-01-15 13:56 UTC by aiwenmo

## Purpose of the pull request

## Brief change log

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

2023-01-15 14:15 UTC, leechor requested changes

2023-01-15 14:15 UTC, leechor commented on dinky-admin/src/main/java/org/dinky/controller/DataBaseController.java
> +            databaseService.updateById(dataBase);
这里可以finally

2023-01-15 14:15 UTC, leechor commented on dinky-admin/src/main/java/org/dinky/service/impl/DataBaseServiceImpl.java
> +            isHealthy = false;
又抛出去，这里逻辑就没什么意义了。

2023-01-15 14:15 UTC, leechor commented on dinky-admin/src/main/java/org/dinky/service/impl/DataBaseServiceImpl.java
> +                return save(dataBase);
建议catch, 打印，接下来save

2023-01-16 00:56 UTC, zackyoungh approved these changes
LGTM

2023-01-16 01:18 UTC, wmtbnbo commented
既然可以在心跳检测的方法里面做异常捕获建议直接在该方法捕获异常打印，外部引用该方法直接通过布尔值判断即可，毕竟测试是引用的另一个方法，而且在前端的ui小图标里面可以看到数据库状态，此处的异常只需要保留在日志里面方便查找就行。
![1673831878751](https://user-images.githubusercontent.com/44955013/212579237-a2af603c-c8a2-4fac-a82f-78ad8183224e.png)

2023-01-16 14:45 UTC, aiwenmo commented
> 既然可以在心跳检测的方法里面做异常捕获建议直接在该方法捕获异常打印，外部引用该方法直接通过布尔值判断即可，毕竟测试是引用的另一个方法，而且在前端的ui小图标里面可以看到数据库状态，此处的异常只需要保留在日志里面方便查找就行。 ![1673831878751](https://user-images.githubusercontent.com/44955013/212579237-a2af603c-c8a2-4fac-a82f-78ad8183224e.png)

本PR已实现异常提示

2023-01-16 15:32 UTC, leechor reviewed
LGTM

2023-01-16 15:33 UTC, leechor commented
> > 既然可以在心跳检测的方法里面做异常捕获建议直接在该方法捕获异常打印，外部引用该方法直接通过布尔值判断即可，毕竟测试是引用的另一个方法，而且在前端的ui小图标里面可以看到数据库状态，此处的异常只需要保留在日志里面方便查找就行。 ![1673831878751](https://user-images.githubusercontent.com/44955013/212579237-a2af603c-c8a2-4fac-a82f-78ad8183224e.png)
> 
> 本PR已实现异常提示

这个建议对的，显示只是瞬间的，日志可以用于事后排查。

2023-01-16 15:48 UTC, merged