[refactor][alert] refactor alert module
DataLinkDC/dinky pull request #1577
Opened 2023-01-27 03:04 UTC by zhu-mingye

## Purpose of the pull request

## Brief change log

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

2023-01-27 07:56 UTC, leechor commented
LGTM

2023-01-29 06:46 UTC, zackyoungh commented on dinky-alert/dinky-alert-base/src/main/java/org/dinky/alert/AlertTypeEnum.java
> +    WECHAT("FeiShu");
名字错了

2023-01-29 06:47 UTC, zackyoungh approved these changes
LGTM

2023-01-29 06:56 UTC, leechor approved these changes

2023-01-29 06:56 UTC, leechor commented on dinky-alert/dinky-alert-base/src/main/java/org/dinky/alert/AlertTypeEnum.java
> +public enum AlertTypeEnum {
AlertType without Enum is better.

2023-01-29 06:56 UTC, leechor commented on dinky-alert/dinky-alert-base/src/main/java/org/dinky/alert/ShowType.java
> +    TABLE(0, "table"),
same code as Markdown?

2023-01-29 07:16 UTC, aiwenmo requested changes
Please remove AlertTypeEnum

2023-01-29 08:10 UTC, aiwenmo approved these changes

2023-01-30 15:36 UTC, merged