[Feature][web] added user list for dinky-web module
DataLinkDC/dinky pull request #1769
Opened 2023-03-23 10:33 UTC by zhu-mingye

## Purpose of the pull request

- added user list
- added theme check

## Brief change log

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

2023-03-23 10:34 UTC, Zzm0809 commented
![image](https://user-images.githubusercontent.com/58576849/227963270-e984b351-7860-4293-bd29-2731c08c1264.png)

![image](https://user-images.githubusercontent.com/58576849/227963345-3f5ddb54-78b2-465a-a08b-0b92fb4037ea.png)

![image](https://user-images.githubusercontent.com/58576849/227963403-e485b579-9d62-4a03-9c47-759fb9b36f2a.png)

![image](https://user-images.githubusercontent.com/58576849/227963937-cf6c70b2-4b96-447e-aa3d-091509a9f071.png)


![image](https://user-images.githubusercontent.com/58576849/227964038-4999b373-23d9-415b-ad4c-bd0d825ed952.png)


![image](https://user-images.githubusercontent.com/58576849/227964231-4b5f5b32-6e97-49ea-ae9e-350acd673e8f.png)

2023-03-24 15:17 UTC, aiwenmo commented
Why use two tone icon?

2023-03-24 15:30 UTC, aiwenmo requested changes
Is it compatible dlink-web?

2023-03-24 15:30 UTC, aiwenmo commented on dinky-admin/src/main/java/org/dinky/controller/UserController.java
> +            return Result.failed("删除失败");
Use English.

2023-03-24 15:30 UTC, aiwenmo commented on dinky-admin/src/main/java/org/dinky/controller/UserController.java
>      }
Use English.

2023-03-24 15:30 UTC, aiwenmo commented on dinky-admin/src/main/java/org/dinky/service/impl/UserServiceImpl.java
> +            return Result.failed("用户授权角色失败");
Use English.

2023-03-24 15:30 UTC, aiwenmo commented on dinky-web/src/components/Icons/CustomIcons.tsx
> +  return <>
DangerDeleteIcon has a clearer meaning than CustomDeleteIcon.

2023-03-25 02:56 UTC, zhu-mingye commented
> Is it compatible dlink-web?

If compatibility is required, then refactor directly on dlink-web, otherwise, both web modules need to be modified at the same time

2023-03-25 02:59 UTC, zhu-mingye commented on dinky-web/src/components/Icons/CustomIcons.tsx
> +  return <>
> DangerDeleteIcon has a clearer meaning than CustomDeleteIcon.

ok i will be modify

2023-03-25 03:02 UTC, zhu-mingye commented
> Why use two tone icon?

I think using TwoTone icons makes the page more beautiful. If TwoTone Icons can’t satisfy you, you can add a custom Icon

2023-03-27 15:12 UTC, aiwenmo approved these changes
LGTM

2023-03-27 15:21 UTC, leechor commented
LGTM

2023-03-28 00:40 UTC, merged