refactor alert instance && support sms(web)
DataLinkDC/dinky pull request #1999
Opened 2023-05-31 08:33 UTC by zhu-mingye

## Purpose of the pull request

- refactor alert instance
- support sms(web) 
  - [ x ] The front-end code has been completed
  - [ ] The remaining sending methods of the back-end code have not been implemented yet, marked as todo, and will be implemented later

## Brief change log

### list
![image](https://github.com/DataLinkDC/dinky/assets/58576849/094c7e18-daef-44d3-9de4-9a0a0d0d0f50)
![image](https://github.com/DataLinkDC/dinky/assets/58576849/00bceaf2-1d2d-4b31-b87b-36775ed7bbc3)

### create
![create](https://github.com/DataLinkDC/dinky/assets/58576849/b9d66531-a779-4f63-b5f0-4928c22a5848)

### modify
![image](https://github.com/DataLinkDC/dinky/assets/58576849/f65c2d40-0fbc-4dfa-b2c4-05af0a2dbbf2)
![image](https://github.com/DataLinkDC/dinky/assets/58576849/e38a0082-faf6-4ba1-a1be-f2a7e49ba25e)
![image](https://github.com/DataLinkDC/dinky/assets/58576849/09d30369-51fe-4b29-a8e6-125b01d53e82)
![image](https://github.com/DataLinkDC/dinky/assets/58576849/2a6f80ce-cac5-41d6-a2ad-557008dc4658)
![image](https://github.com/DataLinkDC/dinky/assets/58576849/a133dcdb-4f88-4321-980c-4389d5b80094)

2023-05-31 08:53 UTC, zackyoungh requested changes

2023-05-31 08:53 UTC, zackyoungh commented on dinky-alert/dinky-alert-sms/src/main/java/org/dinky/alert/sms/SmsSender.java
> +    SmsBlend smsSendFactory = null;
建议使用final

2023-05-31 08:53 UTC, zackyoungh commented on dinky-alert/dinky-alert-wechat/pom.xml
> +            <scope>${scope.runtime}</scope>
这个只有在test中引用

2023-05-31 09:15 UTC, zhu-mingye commented on dinky-alert/dinky-alert-sms/src/main/java/org/dinky/alert/sms/SmsSender.java
> +    SmsBlend smsSendFactory = null;
> 建议使用final

无参构造中需要根据 厂商类型获取 配置对象 和 发送工厂对象

2023-05-31 09:33 UTC, leechor reviewed
LGTM

2023-05-31 09:33 UTC, leechor commented on dinky-web/src/pages/RegCenter/Alert/AlertInstance/components/AlertTypeChoose/InstanceForm/Sms/index.tsx
> +      case 1:
here maybe enum type better?

2023-05-31 12:17 UTC, zhu-mingye commented on dinky-web/src/pages/RegCenter/Alert/AlertInstance/components/AlertTypeChoose/InstanceForm/Sms/index.tsx
> +      case 1:
OK，i will use enum to support it

2023-06-01 01:49 UTC, zackyoungh approved these changes
LGTM

2023-06-01 05:31 UTC, merged