Add jar sql
DataLinkDC/dinky pull request #2317
Opened 2023-09-15 09:29 UTC by zackyoungh

## Purpose of the pull request

1. Custom SQL Submit jar
> syntax:
``` sql
EXECUTE JAR WITH ( 
'uri'='...',
'main-class'='...',
'args'='...',-- 可选
'parallelism'='...',-- 可选
'savepoint-path'='...' -- 可选
)
```

> eg:
``` sql
EXECUTE JAR WITH ( 
'uri'='file:///C:/Users/ZackYoung/Downloads/paimon-flink-1.16-0.5-20230818.001833-127.jar',
'main-class'='org.apache.paimon.flink.action.FlinkActions',
'args'='mysql-sync-table --warehouse hdfs://10.8.16.157:9000/save --database cdc-test --table cdc_test1 --primary-keys id --mysql-conf hostname=121.5.136.161 --mysql-conf port=3371 --mysql-conf username=root --mysql-conf password=dinky --mysql-conf database-name=cdc-test --mysql-conf table-name=table_1 --mysql-conf server-time-zone=Asia/Shanghai --table-conf bucket=4 --table-conf changelog-producer=input --table-conf sink.parallelism=1',
'parallelism'='',
'savepoint-path'='' 
)
```

2023-09-15 13:31 UTC, aiwenmo requested changes

2023-09-15 13:31 UTC, aiwenmo commented on dinky-client/dinky-client-1.16/src/main/java/org/dinky/executor/CustomTableEnvironmentImpl.java
>          } else {
Is the code duplicated?

2023-09-15 13:31 UTC, aiwenmo commented on dinky-executor/src/test/java/org/dinky/trans/ExecuteJarParseStrategyTest.java
> +                + "'args'='mysql-sync-table --warehouse hdfs://10.8.16.157:9000/save --database cdc-test --table cdc_test1 --primary-keys id --mysql-conf hostname=121.5.136.161 --mysql-conf port=3371
Please use 127.0.0.1

2023-09-15 13:56 UTC, leechor commented on dinky-core/src/main/java/org/dinky/explainer/Explainer.java
> -                record.setType("DATASTREAM");
does here affect batch model?

2023-09-15 13:56 UTC, leechor commented on dinky-core/src/main/java/org/dinky/job/JobManager.java
> -                            break;
assure this logic @aiwenmo

2023-09-16 12:26 UTC, aiwenmo commented on dinky-core/src/main/java/org/dinky/job/JobManager.java
> -                            break;
Restore first, I'm refactoring.

2023-10-20 09:34 UTC, closed without merging