[Fix][Flink]Fix local model bug and FlinkSql task type selected by default
DataLinkDC/dinky pull request #2403
Opened 2023-10-18 12:31 UTC by leechor

2023-10-18 14:06 UTC, aiwenmo requested changes

2023-10-18 14:06 UTC, aiwenmo commented on dinky-executor/src/main/java/org/dinky/executor/ExecutorConfig.java
>      }
Remote: standalone, yarn-session,k8s-session;
Local:local,yarn-perjob,yarn-application,k8s-application

2023-10-18 14:06 UTC, aiwenmo commented on dinky-executor/src/main/java/org/dinky/executor/ExecutorFactory.java
>          return new LocalStreamExecutor(ExecutorConfig.DEFAULT);
The default result of getExecutor is LocalStreamExecutor, No need for explicit explanation again.

2023-10-19 01:17 UTC, zhu-mingye approved these changes
LGTM

2023-10-19 06:03 UTC, aiwenmo approved these changes
LGTM

2023-10-19 06:04 UTC, merged