[Optimize][Web]optimize_web_catalog
DataLinkDC/dinky pull request #2457
Opened 2023-10-30 09:45 UTC by zackyoungh

## Purpose of the pull request

## Brief change log
![image](https://github.com/DataLinkDC/dinky/assets/42713096/f84472f2-9108-4cce-9549-05d27f9a6966)
![image](https://github.com/DataLinkDC/dinky/assets/42713096/32415402-b7b4-4865-bc65-8c5097d11601)

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

2023-10-30 09:56 UTC, zhu-mingye approved these changes
LGTM

2023-10-30 14:22 UTC, aiwenmo requested changes

2023-10-30 14:22 UTC, aiwenmo commented on dinky-executor/src/main/java/org/dinky/executor/VariableManager.java
This can cause variable conflicts between different tasks.

2023-10-31 06:08 UTC, zhu-mingye commented
@aiwenmo PTAL

2023-10-31 09:22 UTC, aiwenmo approved these changes
LGTM

2023-10-31 09:22 UTC, merged