refactor data-studio's bottom job exec history
DataLinkDC/dinky pull request #2575
Opened 2023-11-25 16:11 UTC by Zzm0809

## Purpose of the pull request

## Brief change log

## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

2023-11-26 07:26 UTC, gaoyan1998 commented
LGTM

2023-11-26 12:30 UTC, aiwenmo requested changes

2023-11-26 12:30 UTC, aiwenmo commented on dinky-core/src/main/java/org/dinky/job/JobConfig.java
>              dataType = "boolean",
The front-end does not require this parameter, the back-end requires it.

2023-11-27 01:11 UTC, Zzm0809 commented
@aiwenmo PTAL

2023-11-27 01:31 UTC, Zzm0809 commented
@aiwenmo PTAL

2023-11-27 13:04 UTC, aiwenmo approved these changes
LGTM

2023-11-27 13:04 UTC, merged