修复prevState和data.lastUpdateStep空值导致方法报错
DataLinkDC/dinky pull request #3145
Opened 2024-02-05 07:33 UTC by yangzehan

![10080806e7f768d58e770c7aa0bbdd7](https://github.com/DataLinkDC/dinky/assets/76773988/35a0aa3d-af70-4946-9e81-99cecce1cfeb)
![e8dc94cce5ca74abeda56be9deb497b](https://github.com/DataLinkDC/dinky/assets/76773988/ac262e9a-bc9f-46ac-926f-44f5238a351a)
![image](https://github.com/DataLinkDC/dinky/assets/76773988/50af44cb-a8f7-47f7-b5c1-4e59cf292fba)

2024-02-05 14:22 UTC, aiwenmo commented
This branch has conflicts that must be resolved.

2024-02-06 01:45 UTC, Zzm0809 commented on dinky-web/src/pages/DataStudio/BottomContainer/Console/ConsoleContent.tsx
> +        {node.status == 'FAILED' && (
why change it??

2024-02-06 13:19 UTC, aiwenmo requested changes
Please rebase this branch onto dev branch.

2024-02-14 12:21 UTC, Zzm0809 commented on dinky-web/src/pages/DataStudio/BottomContainer/Console/ConsoleContent.tsx
> +        if (prevState && prevState.key == data.lastUpdateStep.key) {
data.lastUpdateStep.key 可能为 undefined

2024-02-18 03:31 UTC, closed without merging