[Feature-38938][core][admin][web] Flink SQL task Support insert result preview
DataLinkDC/dinky pull request #3897
Opened 2024-11-02 15:04 UTC by MactavishCui

## Purpose of the pull request
This pull request is aimed at implementing the feature of insert result preview.

## Brief change log

A customized connector class is added to write insert result into accumulator.
A mock statement explainer is added to convert insert statement into mock.
Some related changes of model core and admin.
## Verify this pull request

This pull request is code cleanup without any test coverage.

*(or)*

This pull request is already covered by existing tests, such as *(please describe tests)*.

(or)

This change added tests and can be verified as follows:

2024-11-02 15:07 UTC, MactavishCui commented
[](url)

2024-11-09 07:04 UTC, Zzm0809 requested changes

2024-11-09 07:04 UTC, Zzm0809 commented on dinky-core/src/main/java/org/dinky/explainer/mock/MockStatementExplainer.java
> +    public static final String MOCK_SQL_TEMPLATE = "CREATE TABLE {0} ({1}) WITH ({2})";
如果配置了catalog ，第二次执行是否会报错表已存在？

2024-11-09 10:01 UTC, MactavishCui commented on dinky-core/src/main/java/org/dinky/explainer/mock/MockStatementExplainer.java
> +    public static final String MOCK_SQL_TEMPLATE = "CREATE TABLE {0} ({1}) WITH ({2})";
感谢您指出的问题！我稍晚些时候将修正这一问题并在测试通过后更新PR。

2024-11-09 11:42 UTC, MactavishCui commented on dinky-core/src/main/java/org/dinky/explainer/mock/MockStatementExplainer.java
> +    public static final String MOCK_SQL_TEMPLATE = "CREATE TABLE {0} ({1}) WITH ({2})";
[9ff2bb3](https://github.com/DataLinkDC/dinky/pull/3897/commits/9ff2bb364beed61915e7e4d7903a213328bbea2b) 中提交了关于解决此处问题的新的代码变更，辛苦老师们review并提出宝贵意见~

2024-11-09 15:02 UTC, Zzm0809 commented
你能针对此扩展功能补充一下该文档吗?

2024-11-10 14:30 UTC, Zzm0809 requested changes

2024-11-10 14:30 UTC, Zzm0809 commented on dinky-core/src/main/java/org/dinky/explainer/mock/MockStatementExplainer.java
> +    public static final String MOCK_SQL_TEMPLATE = "CREATE TABLE IF NOT EXISTS {0} ({1}) WITH ({2})";
如果结构变更了呢？建议先删除在创建。或者直接建临时表

2024-11-10 17:45 UTC, MactavishCui commented on dinky-core/src/main/java/org/dinky/explainer/mock/MockStatementExplainer.java
> +    public static final String MOCK_SQL_TEMPLATE = "CREATE TABLE IF NOT EXISTS {0} ({1}) WITH ({2})";
非常感谢您提供的建议！在新的commit中，CREATE DDL前新增了DROP IF EXITS的操作，同时为需要MOCK的表增加了mock_sink_前缀，以同改写前的表单命名区分。辛苦老师review~

2024-11-10 17:46 UTC, MactavishCui commented
> 你能针对此扩展功能补充一下该文档吗?

Sure！我将于近两天更新docs部分，补充当前拓展功能的效果、达成的前提等信息。

2024-11-11 03:34 UTC, aiwenmo approved these changes
LGTM

2024-11-11 03:35 UTC, Zzm0809 commented
> > 你能针对此扩展功能补充一下该文档吗?
> 
> Sure！我将于近两天更新docs部分，补充当前拓展功能的效果、达成的前提等信息。

非常感谢您的贡献, 文档可以后续补充, 单独 pr 以下, 本次新功能 pr 将被合并

2024-11-11 03:36 UTC, Zzm0809 reviewed
LGTM

2024-11-11 03:36 UTC, Zzm0809 approved these changes
LGTM

2024-11-11 03:36 UTC, merged